""" Corrected email model

Revision ID: 09907daafa5f
Revises: 6d24e0d10115
Create Date: 2023-06-30 14:01:06.263352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09907daafa5f'
down_revision = '6d24e0d10115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('date_added',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('date_added',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
